//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiLaarIsch.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEntity
    {
        public System.Guid Id { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string EmergencyNumber { get; set; }
        public HiLaarIsch.Components.GroupLevel GroupLevel { get; set; }
    
        public virtual UserEntity User { get; set; }
    }
}
