//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiLaarIsch.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntity
    {
        public System.Guid Id { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public HiLaarIsch.Components.Role Role { get; set; }
    
        public virtual CustomerEntity Customer { get; set; }
    }
}
